# Generated by Django 3.2.6 on 2021-08-12 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldOrderType', models.CharField(max_length=4, null=True, verbose_name='Ордер')),
            ],
        ),
        migrations.AlterField(
            model_name='notebook',
            name='fieldOrderType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.ordertype', verbose_name='Ордер'),
        ),
    ]
