# Generated by Django 3.2.6 on 2021-08-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20210812_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldTicker', models.CharField(blank=True, max_length=10, null=True, verbose_name='Тикер')),
            ],
            options={
                'verbose_name': 'Тикер',
                'verbose_name_plural': 'Тикеры',
                'ordering': ['-fieldTicker'],
            },
        ),
        migrations.AlterModelOptions(
            name='ordertype',
            options={'ordering': ['-fieldOrderType'], 'verbose_name': 'Ордер', 'verbose_name_plural': 'Ордеры'},
        ),
    ]
