# Generated by Django 3.2.6 on 2021-08-12 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20210812_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='fieldFullName',
            field=models.CharField(default='Нет', max_length=20, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='fieldTicker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.ticker', verbose_name='Тикер'),
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='fieldOrderType',
            field=models.CharField(max_length=4, verbose_name='Ордер'),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='fieldTicker',
            field=models.CharField(default='Нет', max_length=10, verbose_name='Тикер'),
        ),
    ]
