# Generated by Django 3.2.6 on 2021-08-13 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20210812_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldEnterReason', models.CharField(default='Нет', max_length=4, verbose_name='Причина входа')),
            ],
            options={
                'verbose_name': 'Причина входа',
                'verbose_name_plural': 'Причины входа',
                'ordering': ['-fieldEnterReason'],
            },
        ),
        migrations.AlterField(
            model_name='notebook',
            name='fieldEnterReason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.enterreason', verbose_name='Причина входа'),
        ),
    ]
