# Generated by Django 3.2.6 on 2021-08-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_auto_20210813_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterreason',
            name='fieldEnterReason',
            field=models.CharField(default='Нет', max_length=10, verbose_name='Причина входа'),
        ),
    ]
