# Generated by Django 3.2.6 on 2021-08-17 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldBranchName', models.CharField(default='Нет', max_length=100, verbose_name='Отрасль')),
            ],
            options={
                'verbose_name': 'Отрасль',
                'verbose_name_plural': 'Отрасли',
                'ordering': ['-fieldBranchName'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldSectorName', models.CharField(default='Нет', max_length=100, verbose_name='Сектор')),
            ],
            options={
                'verbose_name': 'Сектор',
                'verbose_name_plural': 'Секторы',
                'ordering': ['-fieldSectorName'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldCompanyName', models.CharField(blank=True, max_length=20, null=True, verbose_name='Выбранная стратегия')),
                ('fieldBranch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segment.branch', verbose_name='Отрасль')),
                ('fieldSector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segment.sector', verbose_name='Сектор')),
            ],
            options={
                'verbose_name': 'Сегментация компаний',
                'verbose_name_plural': 'Сементация компаний',
                'ordering': ['-fieldCompanyName'],
            },
        ),
    ]
